### ISSUE TITLE
First Year Tips Page - Course Advice

### ISSUE THREAD

**Issue by ianDesson** [sesa-uottawa/sesa-gatsby#31]
We should add the Course Advice Section to the First Year Tips Page. (Original can be found here: https://sesa-uottawa.herokuapp.com/advice/firstyear)
![image](https://user-images.githubusercontent.com/25931837/69487022-2d017000-0e21-11ea-97ca-9202ca015063.png)
This should be done as a grid that has buttons which allow you to switch between which course is visible (i.e. about the same as the previous implementation). For this to be complete, the user should be able to switch between the advice for each course.

**Comment by ianDesson** [comment]
Something that might be interesting to add/ look into is connecting this with SESA-Notes (will require communicating with Faiz)

**Comment by dannyshwan** [comment]
Feature implemented with #37.
Closing issue for the time being
